name: JaggedAchievements
main: org.jaggy.jaggedachievements.spigot.Jagged
version: 1.3-RELEASE
softdepend: [JaggyGold]
author: Quirkylee, Markjat

permissions:
    jachievements.user:
        description: Allows user to use Jagged Achievements.
        default: true
    jachievements.mod:
        description: Allows access to mod commands
        default: op
    jachievements.exempt:
        description: exempts user from leveling
        default: op
    jachievements.admin:
        description: Allows access to admin commands
        default: op
    jachievements.*:
        description: Wildcard allowing access to everything
        default: op
        children:
            jachievements.user: true
            jachievements.mod: true
            jachievements.admin: true

commands:
   profile:
      description: Show Achievement profiles
      usage: /profile [profile]
   achievements:
      description: Main Command if no args it will display past achievements
      usage: /achievements <past|reload>
   required:
      description: Show the required xp for the next level
      usage: /required